# Generated by Django 5.2.17 on 2026-09-28 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("orchestration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=64)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Evaluation datasets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_id", models.SlugField(max_length=120)),
                ("input_text", models.TextField()),
                ("expected_output", models.TextField(blank=True)),
                ("expected_route", models.CharField(blank=True, max_length=120)),
                ("expected_risk_level", models.CharField(blank=True, max_length=16)),
                ("conversation_turns", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "expected_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_cases",
                        to="knowledge.document",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="evaluations.evaluationdataset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluation cases",
                "ordering": ("dataset", "case_id"),
            },
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("regression", "Regression"),
                            ("smoke", "Smoke"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("metrics_summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "agent_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="orchestration.agentconfig",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="evaluations.evaluationdataset",
                    ),
                ),
                (
                    "model_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="orchestration.aimodelconfig",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluation runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField(default=0.0)),
                ("passed", models.BooleanField(default=False)),
                ("retrieval_passed", models.BooleanField(blank=True, null=True)),
                ("grounding_passed", models.BooleanField(blank=True, null=True)),
                ("grounding_explanation", models.TextField(blank=True)),
                ("memory_passed", models.BooleanField(blank=True, null=True)),
                ("memory_explanation", models.TextField(blank=True)),
                ("crisis_resource_passed", models.BooleanField(blank=True, null=True)),
                ("crisis_resource_explanation", models.TextField(blank=True)),
                ("prediction", models.TextField(blank=True)),
                ("ground_truth", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "evaluation_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="evaluations.evaluationcase",
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluation results",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("value", models.FloatField()),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Metrics",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationcase",
            constraint=models.UniqueConstraint(
                fields=("dataset", "case_id"), name="unique_case_id_per_dataset"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationresult",
            constraint=models.UniqueConstraint(
                fields=("evaluation_run", "evaluation_case"), name="unique_result_per_case_per_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("evaluation_run", "name"), name="unique_metric_name_per_run"
            ),
        ),
    ]
