# Generated by Django 5.2.17 on 2026-09-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "policy_type",
                    models.CharField(
                        blank=True,
                        help_text="Example: keyword, classifier, llm, hybrid",
                        max_length=64,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("rule_json", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Safety policies",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SafetyAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("normal", "Normal"), ("crisis", "Crisis")],
                        db_index=True,
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("allow", "Allow"), ("handoff", "Handoff")],
                        db_index=True,
                        default="allow",
                        max_length=16,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_assessments",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_assessments",
                        to="conversations.message",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="safety.safetypolicy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Safety assessments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SafetyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="safety.safetyassessment",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_events",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Safety events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="safetyassessment",
            index=models.Index(
                fields=["conversation", "stage"], name="safety_safe_convers_8904bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safetyassessment",
            index=models.Index(
                fields=["risk_level", "decision"], name="safety_safe_risk_le_a3cd10_idx"
            ),
        ),
    ]
