# Generated by Django 5.2.17 on 2026-09-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("webpage", "Webpage"),
                            ("file", "File"),
                            ("faq", "FAQ"),
                            ("note", "Note"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("source_uri", models.TextField(blank=True)),
                ("raw_text", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Documents",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status"], name="knowledge_d_status_79949e_idx"),
                    models.Index(fields=["source_type"], name="knowledge_d_source__07195f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("vector_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document chunks",
                "ordering": ("document", "chunk_index"),
            },
        ),
        migrations.CreateModel(
            name="Retrieval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_text", models.TextField()),
                ("top_k", models.PositiveIntegerField(default=5)),
                ("retriever_name", models.CharField(blank=True, max_length=128)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrievals",
                        to="orchestration.agentrun",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrievals",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Retrievals",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RetrievedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveIntegerField()),
                ("score", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrieved_in",
                        to="knowledge.documentchunk",
                    ),
                ),
                (
                    "retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="knowledge.retrieval",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Retrieved documents",
                "ordering": ("rank",),
            },
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="knowledge_d_documen_ea33de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"), name="unique_chunk_index_per_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="retrieveddocument",
            constraint=models.UniqueConstraint(
                fields=("retrieval", "rank"), name="unique_retrieval_rank"
            ),
        ),
    ]
