# Generated by Django 5.2.17 on 2026-09-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("system_prompt", models.TextField()),
                ("temperature", models.FloatField(default=0.7)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Agent configurations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("groq", "Groq"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Gemini"),
                            ("ollama", "Ollama"),
                            ("local", "Local"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("api_key_plaintext", models.TextField(blank=True)),
                ("base_url", models.URLField(blank=True)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chat", "Chat"),
                            ("embeddings", "Embeddings"),
                            ("safety", "Safety"),
                            ("eval", "Eval"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_output_tokens", models.PositiveIntegerField(default=1024)),
                ("timeout_seconds", models.PositiveIntegerField(default=60)),
                ("is_default", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "AI model configurations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("graph_version", models.CharField(blank=True, max_length=64)),
                ("supervisor_decision", models.CharField(blank=True, max_length=128)),
                ("start_node", models.CharField(blank=True, max_length=128)),
                ("end_node", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("handoff", "Handoff"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("final_output", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "supervisor_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_runs",
                        to="orchestration.agentconfig",
                    ),
                ),
                (
                    "triggering_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_runs",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_order", models.PositiveIntegerField()),
                ("node_name", models.CharField(max_length=128)),
                ("agent_name", models.CharField(blank=True, max_length=128)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("route", "Route"),
                            ("safety", "Safety"),
                            ("retrieve", "Retrieve"),
                            ("generate", "Generate"),
                            ("handoff", "Handoff"),
                        ],
                        db_index=True,
                        default="route",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=16,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("tokens_input", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_output", models.PositiveIntegerField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="orchestration.agentrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent steps",
                "ordering": ("agent_run", "step_order"),
            },
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="model_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="orchestration.aimodelconfig",
            ),
        ),
        migrations.CreateModel(
            name="Handoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoffs",
                        to="orchestration.agentrun",
                    ),
                ),
                (
                    "from_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handoffs_from",
                        to="orchestration.agentconfig",
                    ),
                ),
                (
                    "to_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handoffs_to",
                        to="orchestration.agentconfig",
                    ),
                ),
                (
                    "triggered_by_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoffs",
                        to="orchestration.agentstep",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Handoffs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["conversation", "status"], name="orchestrati_convers_90baf9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.UniqueConstraint(
                fields=("agent_run", "step_order"), name="unique_step_order_per_run"
            ),
        ),
    ]
