from knowledge.models import DocumentChunk, RetrievedDocument, Retrieval
from safety.models import SafetyAssessment

from .models import AgentConfig, AgentRun, Handoff


def save_safety_assessment(
    *,
    conversation_id: int,
    message_id: int,
    assessment: dict,
) -> SafetyAssessment:
    risk_level = assessment["risk_level"]

    decision = "handoff" if risk_level == "crisis" else "allow"

    return SafetyAssessment.objects.create(
        conversation_id=conversation_id,
        message_id=message_id,
        stage="input",
        risk_level=risk_level,
        decision=decision,
        categories=assessment.get(
            "relevant_risk_categories",
            [],
        ),
        model_name="",
        reason="Generated by Seher safety assessment.",
        metadata={"recommended_action": assessment.get("recommended_action")},
    )


def save_retrieval(
    *,
    conversation_id: int,
    agent_run_id: int,
    query: str,
    results: list[dict],
) -> Retrieval:
    retrieval = Retrieval.objects.create(
        conversation_id=conversation_id,
        agent_run_id=agent_run_id,
        query_text=query,
        top_k=len(results),
        retriever_name="chroma",
    )

    retrieved_documents = []

    for result in results:
        chunk_id = result["metadata"].get("chunk_id")

        if chunk_id is None:
            continue

        chunk = DocumentChunk.objects.filter(pk=chunk_id).first()

        if not chunk:
            continue

        retrieved_documents.append(
            RetrievedDocument(
                retrieval=retrieval,
                chunk=chunk,
                rank=result["rank"],
                score=result["score"],
                metadata=result["metadata"],
            )
        )

    RetrievedDocument.objects.bulk_create(retrieved_documents)

    return retrieval


def save_handoff(
    *,
    agent_run_id: int,
    from_agent_slug: str,
    to_agent_slug: str,
    reason: str,
    triggered_by_step=None,
):
    from_agent = AgentConfig.objects.get(slug=from_agent_slug)
    to_agent = AgentConfig.objects.get(slug=to_agent_slug)

    return Handoff.objects.create(
        agent_run_id=agent_run_id,
        from_agent=from_agent,
        to_agent=to_agent,
        reason=reason,
        triggered_by_step=triggered_by_step,
    )
